"""empty message

Revision ID: 99bc8343a1c6
Revises: d1e21fe53771
Create Date: 2023-01-19 13:07:35.158822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bc8343a1c6'
down_revision = 'd1e21fe53771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handled_create_notif_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('notification', sa.String(), nullable=False),
    sa.Column('handled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['notification'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handled_create_notif_event')
    # ### end Alembic commands ###
